from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from pydantic import BaseModel
from sqlalchemy.orm import Session

from db.database import get_db
from db.models import AlertEventModel
from services.alerts import (
    build_github_issue_payload,
    build_jira_issue_payload,
    create_github_issue,
    create_jira_issue,
    send_webhook_alert,
    store_alert_event,
)
from services.auth_guard import verify_access_token
from services.audit import write_audit_event

router = APIRouter(prefix="/api/alerts", tags=["alerts"])


class AlertDispatchRequest(BaseModel):
    event_type: str
    severity: str = "INFO"
    payload: dict = {}


class TicketRequest(BaseModel):
    title: str
    body: str
    labels: list[str] = []


@router.get("")
async def list_alert_events(request: Request, db: Session = Depends(get_db)):
    verify_access_token(request, required_scope="read")
    rows = db.query(AlertEventModel).order_by(AlertEventModel.created_at.desc()).limit(200).all()
    return [
        {
            "id": row.id,
            "event_type": row.event_type,
            "severity": row.severity,
            "payload": row.payload,
            "created_at": row.created_at.isoformat(),
        }
        for row in rows
    ]


@router.post("/dispatch")
async def dispatch_alert(payload: AlertDispatchRequest, request: Request, db: Session = Depends(get_db)):
    token = verify_access_token(request, required_scope="write")
    actor = str(token.get("sub", "unknown"))
    row = store_alert_event(db, event_type=payload.event_type, severity=payload.severity.upper(), payload=payload.payload)
    delivered = await send_webhook_alert(event_type=row.event_type, severity=row.severity, payload=row.payload)
    write_audit_event(
        event_type="alert.dispatched",
        actor=actor,
        details={"alert_id": row.id, "event_type": row.event_type, "severity": row.severity, "delivered": delivered},
    )
    return {"alert_id": row.id, "delivered": delivered}


@router.post("/integrations/github/issue-template")
async def github_issue_template(request: Request):
    verify_access_token(request, required_scope="write")
    return build_github_issue_payload(
        title="[EMET] Critical verified vulnerability",
        body="Generated by EMET defensive workflow. Review evidence and remediation priority.",
    )


@router.post("/integrations/github/issue")
async def github_issue_create(payload: TicketRequest, request: Request):
    token = verify_access_token(request, required_scope="write")
    actor = str(token.get("sub", "unknown"))
    ok, ref = await create_github_issue(title=payload.title, body=payload.body, labels=payload.labels)
    write_audit_event(event_type="alert.github.issue", actor=actor, details={"ok": ok, "ref": ref})
    return {"ok": ok, "reference": ref}


@router.post("/integrations/jira/issue-template")
async def jira_issue_template(request: Request):
    verify_access_token(request, required_scope="write")
    return build_jira_issue_payload(
        summary="EMET: Critical verified vulnerability",
        description="Generated by EMET defensive workflow. Validate evidence and triage.",
    )


@router.post("/integrations/jira/issue")
async def jira_issue_create(payload: TicketRequest, request: Request):
    token = verify_access_token(request, required_scope="write")
    actor = str(token.get("sub", "unknown"))
    ok, ref = await create_jira_issue(summary=payload.title, description=payload.body)
    write_audit_event(event_type="alert.jira.issue", actor=actor, details={"ok": ok, "ref": ref})
    return {"ok": ok, "reference": ref}
